# https://doc.traefik.io/traefik/providers/docker/
# https://doc.traefik.io/traefik/operations/dashboard/
# https://doc.traefik.io/traefik/migration/v1-to-v2/

version: "3.8"

services:
  whoami:
    image: "traefik/whoami"
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.internal`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80" # swarm init 
    networks:
      - traefiknet

networks:
  traefiknet:
    external:
      true