version: '3.3'

services:
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pF4b7kjvywhAZc6u
      MYSQL_DATABASE: exampledatabase
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: LfBMZa3q3ctnKVJ2

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8080:80"
    restart: always
    environment: 
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: LfBMZa3q3ctnKVJ2
      PMA_HOST: db

volumes:
    db_data: {}