version: '3.1'

services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: LfBMZa3q3ctnKVJ2
      ACCEPT_EULA: Y