version: '3.1'

services:
  db:
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: LfBMZa3q3ctnKVJ2

  mongo-express:
    depends_on:
      - db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: LfBMZa3q3ctnKVJ2