# https://doc.traefik.io/traefik/providers/docker/
# https://doc.traefik.io/traefik/routing/entrypoints/
# https://doc.traefik.io/traefik/operations/dashboard/
# https://doc.traefik.io/traefik/migration/v1-to-v2/
# https://doc.traefik.io/traefik/middlewares/http/basicauth/

version: "3.8"

services:

  traefik:
    image: "traefik:v2.9"
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      #- "--log.level=DEBUG"
      # - --providers.docker.endpoint=tcp://127.0.0.1:2377
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.useBindPortIP=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefiknet
      # - --providers.docker.defaultRule=Host(`{{ .Name }}.{{ index .Labels \"customLabel\"}}`)
      - --providers.docker.swarmModeRefreshSeconds=10
      - --providers.docker.httpClientTimeout=300
      - --providers.docker.watch=true
      - --entrypoints.web.address=:80
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # - --entrypoints.websecure.address=:443
      - --api.dashboard=true 
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefiknet

  whoami:
    image: "traefik/whoami"
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.internal`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80" # swarm init
      - "traefik.http.routers.whoami.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$RgkOrgtI$$5XDTS7phNS6XCyzP5AhL00" # openssl passwd -apr1
    networks:
      - traefiknet

networks:
  traefiknet:
    external:
      true