version: "3.8"

services:
  
  whoami:
    image: traefik/whoami:v1.8
    deploy:
      mode: replicated
      replicas: 3
      # placement:
      #   constraints:
      #     - node.role == manager
      resources:
        limits:
          cpus: '0.01'
          memory: 50MB
        reservations:
          cpus: '0.001'
          memory: 5MB
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.docker.lbswarm=true

      # HTTP
      - "traefik.http.routers.http-whoami-router.priority=2"
      - "traefik.http.routers.http-whoami-router.service=whoami"
      - "traefik.http.routers.http-whoami-router.entrypoints=web" # bu satır kapalı iken bütün portları dinler.
      - "traefik.http.routers.http-whoami-router.rule=Host(`whoami.docker.internal`)"
      - "traefik.http.routers.http-whoami-router.middlewares=https-whoami-middlewares"

      # HTTPS
      - "traefik.http.routers.https-whoami-router.priority=1"
      - "traefik.http.routers.https-whoami-router.service=whoami"
      - "traefik.http.routers.https-whoami-router.entrypoints=websecure"
      - "traefik.http.routers.https-whoami-router.rule=Host(`whoami.docker.internal`)"
      - "traefik.http.routers.https-whoami-router.tls=true"
      - "traefik.http.routers.https-whoami-router.tls.certresolver=myresolver"
      - "traefik.http.routers.https-whoami-router.middlewares=https-whoami-middlewares"

      # Traefik Chain
      # - "traefik.http.middlewares.https-whoami-middlewares.chain.middlewares=whoami-https-only,whoami-auth-users,whoami-known-ips"
      - "traefik.http.middlewares.https-whoami-middlewares.chain.middlewares=whoami-https-only"
      - "traefik.http.middlewares.whoami-https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.whoami-auth-users.basicauth.users=admin:$$apr1$$RgkOrgtI$$5XDTS7phNS6XCyzP5AhL00" # openssl passwd -apr1
      - "traefik.http.middlewares.whoami-known-ips.ipwhitelist.sourceRange=192.168.200.135,10.0.2.1/16"

    networks:
      - traefiknet
      - netmon

networks:
  traefiknet:
    external: true
  netmon:
    external: true
